### ISSUE TITLE
Investigate locking issues

### ISSUE THREAD

**Issue by mjpitz** [depscloud/tracker#39]
In the latest set of changes I made to the charts repository, I noticed some interesting locking messages:

```
time="2020-01-12T18:56:39Z" level=error msg="database table is locked"
time="2020-01-12T18:56:39Z" level=error msg="database table is locked"
time="2020-01-12T18:56:39Z" level=error msg="database table is locked"
time="2020-01-12T18:56:39Z" level=error msg="database table is locked"
time="2020-01-12T18:56:39Z" level=error msg="database table is locked"
time="2020-01-12T18:56:39Z" level=error msg="database table is locked"
time="2020-01-12T18:56:39Z" level=error msg="database table is locked"
time="2020-01-12T18:56:39Z" level=error msg="database table is locked"
time="2020-01-12T18:56:39Z" level=error msg="database table is locked"
time="2020-01-12T18:56:39Z" level=error msg="database table is locked"
time="2020-01-12T18:56:39Z" level=error msg="database table is locked"
time="2020-01-12T18:56:39Z" level=error msg="[service.source] rpc error: code = Internal desc = failed to insert new edges"
```

I'll need to take some time to investigate this log.

**Comment by mjpitz** [comment]
Starting to understand a little more about this.

Because of the way the Track method is implemented, it's possible for two transactions to deadlock one another. I suspect is that this problem will lessen with the k3 work, but remain a problem to some extent.

Current line of thinking is to build on the k3 work and improve the way `SourceService#Track` is currently implemented.

**Comment by mjpitz** [comment]
Confirmed that adding support for k3 does alleviate some of the deadlocks, but they still do happen. Here are a few more improvements that I think we can do:

* only update a rows when there is something to update (i.e. if `!bytes.Equal`).
* retry on deadlocks, but be sure to exponentially backoff

**Comment by MadhuvanthG** [comment]
Happy to take this up as I'm already doing some work around the DB with #24. Are we able to reproduce this? That would be handy or if you could expand on this more

> Because of the way the Track method is implemented, it's possible for two transactions to deadlock one another.

**Comment by mjpitz** [comment]
@MadhuvanthG feel free to take a look at implementing the fixes. I have a pretty good idea of what's happening. More or less you have two transactions open operating on an overlapping keyset of size N. As each transaction works through their keyset, they are completely unaware of the other. One transaction processes Key 1. The other transaction processes Key 2. Eventually, transaction 1 wants to process Key 2, but it's currently locked by the other transaction. Eventually, the other transaction wants to process Key 1, but it's currently locked by the first. Hence the deadlock.

There are probably a few other ways to address this issue, but the exponential backoff on retry seemed fine. I came across a great open-source library for doing exponential backoffs in go a while back. You can see it in use here: https://github.com/mjpitz/paxos/blob/master/internal/server/proposer.go#L8

**Comment by mjpitz** [comment]
I added retry logic a little while ago. This should largely resolved.
